package net.fluffybumblebee.quarkcrystals.block;

import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.fabricmc.fabric.api.registry.OxidizableBlocksRegistry;
import net.fluffybumblebee.quarkcrystals.block.custom.*;
import net.fluffybumblebee.quarkcrystals.util.ArrayDiscriminatorUtil;
import net.fluffybumblebee.quarkcrystals.util.IdentifierUtil;
import net.minecraft.item.BlockItem;
import net.minecraft.item.ItemGroup;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;

public class QCBlocks {

    public static final CorundumCluster BLACK_CLUSTER = new CorundumCluster();
    public static final CorundumCluster BLUE_CLUSTER = new CorundumCluster();
    public static final CorundumCluster CYAN_CLUSTER = new CorundumCluster();
    public static final CorundumCluster GREEN_CLUSTER = new CorundumCluster();
    public static final CorundumCluster INDIGO_CLUSTER = new CorundumCluster();
    public static final CorundumCluster ORANGE_CLUSTER = new CorundumCluster();
    public static final CorundumCluster RED_CLUSTER = new CorundumCluster();
    public static final CorundumCluster PINK_CLUSTER = new CorundumCluster();
    public static final CorundumCluster WHITE_CLUSTER = new CorundumCluster();
    public static final CorundumCluster YELLOW_CLUSTER = new CorundumCluster();
    public static final CorundumCluster PURPLE_CLUSTER = new CorundumCluster();
    public static final CorundumCluster BROWN_CLUSTER = new CorundumCluster();

    public static final CorundumBlock BLACK_CORUNDUM = new CorundumBlock(false, 1);
    public static final CorundumBlock BLUE_CORUNDUM = new CorundumBlock(false, 2);
    public static final CorundumBlock GREEN_CORUNDUM = new CorundumBlock(false, 3);
    public static final CorundumBlock INDIGO_CORUNDUM = new CorundumBlock(false, 4);
    public static final CorundumBlock ORANGE_CORUNDUM = new CorundumBlock(false, 5);
    public static final CorundumBlock RED_CORUNDUM = new CorundumBlock(false, 6);
    public static final CorundumBlock PINK_CORUNDUM = new CorundumBlock(false, 7);
    public static final CorundumBlock WHITE_CORUNDUM = new CorundumBlock(false, 8);
    public static final CorundumBlock YELLOW_CORUNDUM = new CorundumBlock(false, 9);
    public static final CorundumBlock CYAN_CORUNDUM = new CorundumBlock(false, 10);
    public static final CorundumBlock PURPLE_CORUNDUM = new CorundumBlock(false, 11);
    public static final CorundumBlock BROWN_CORUNDUM = new CorundumBlock(false, 12);

    public static final CrystalBlock BLACK_CRYSTAL = new CrystalBlock();
    public static final CrystalBlock BLUE_CRYSTAL = new CrystalBlock();
    public static final CrystalBlock CYAN_CRYSTAL = new CrystalBlock();
    public static final CrystalBlock GREEN_CRYSTAL = new CrystalBlock();
    public static final CrystalBlock INDIGO_CRYSTAL = new CrystalBlock();
    public static final CrystalBlock ORANGE_CRYSTAL = new CrystalBlock();
    public static final CrystalBlock RED_CRYSTAL = new CrystalBlock();
    public static final CrystalBlock PINK_CRYSTAL = new CrystalBlock();
    public static final CrystalBlock WHITE_CRYSTAL = new CrystalBlock();
    public static final CrystalBlock YELLOW_CRYSTAL = new CrystalBlock();
    public static final CrystalBlock PURPLE_CRYSTAL = new CrystalBlock();
    public static final CrystalBlock BROWN_CRYSTAL = new CrystalBlock();

    public static final CorundumCrystalPane BLACK_CORUNDUM_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane BLUE_CORUNDUM_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane CYAN_CORUNDUM_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane GREEN_CORUNDUM_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane INDIGO_CORUNDUM_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane ORANGE_CORUNDUM_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane RED_CORUNDUM_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane PINK_CORUNDUM_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane WHITE_CORUNDUM_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane YELLOW_CORUNDUM_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane PURPLE_CORUNDUM_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane BROWN_CORUNDUM_PANE = new CorundumCrystalPane();

    public static final CorundumCrystalPane BLACK_CRYSTAL_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane BLUE_CRYSTAL_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane CYAN_CRYSTAL_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane GREEN_CRYSTAL_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane INDIGO_CRYSTAL_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane ORANGE_CRYSTAL_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane RED_CRYSTAL_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane PINK_CRYSTAL_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane WHITE_CRYSTAL_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane YELLOW_CRYSTAL_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane PURPLE_CRYSTAL_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane BROWN_CRYSTAL_PANE = new CorundumCrystalPane();

    public static final CorundumBlock WAXED_BLACK_CORUNDUM = new CorundumBlock(true, 1);
    public static final CorundumBlock WAXED_BLUE_CORUNDUM = new CorundumBlock(true, 2);
    public static final CorundumBlock WAXED_CYAN_CORUNDUM = new CorundumBlock(true, 10);
    public static final CorundumBlock WAXED_GREEN_CORUNDUM = new CorundumBlock(true, 3);
    public static final CorundumBlock WAXED_INDIGO_CORUNDUM = new CorundumBlock(true, 4);
    public static final CorundumBlock WAXED_ORANGE_CORUNDUM = new CorundumBlock(true, 5);
    public static final CorundumBlock WAXED_RED_CORUNDUM = new CorundumBlock(true, 6);
    public static final CorundumBlock WAXED_PINK_CORUNDUM = new CorundumBlock(true, 7);
    public static final CorundumBlock WAXED_WHITE_CORUNDUM = new CorundumBlock(true, 8);
    public static final CorundumBlock WAXED_YELLOW_CORUNDUM = new CorundumBlock(true, 9);
    public static final CorundumBlock WAXED_PURPLE_CORUNDUM = new CorundumBlock(true, 11);
    public static final CorundumBlock WAXED_BROWN_CORUNDUM = new CorundumBlock(true, 12);

    public static final CorundumCrystalSlab BLACK_CORUNDUM_SLAB = new CorundumCrystalSlab();
    public static final CorundumCrystalSlab BLUE_CORUNDUM_SLAB = new CorundumCrystalSlab();
    public static final CorundumCrystalSlab CYAN_CORUNDUM_SLAB = new CorundumCrystalSlab();
    public static final CorundumCrystalSlab GREEN_CORUNDUM_SLAB = new CorundumCrystalSlab();
    public static final CorundumCrystalSlab INDIGO_CORUNDUM_SLAB = new CorundumCrystalSlab();
    public static final CorundumCrystalSlab ORANGE_CORUNDUM_SLAB = new CorundumCrystalSlab();
    public static final CorundumCrystalSlab RED_CORUNDUM_SLAB = new CorundumCrystalSlab();
    public static final CorundumCrystalSlab PINK_CORUNDUM_SLAB = new CorundumCrystalSlab();
    public static final CorundumCrystalSlab WHITE_CORUNDUM_SLAB = new CorundumCrystalSlab();
    public static final CorundumCrystalSlab YELLOW_CORUNDUM_SLAB = new CorundumCrystalSlab();
    public static final CorundumCrystalSlab PURPLE_CORUNDUM_SLAB = new CorundumCrystalSlab();
    public static final CorundumCrystalSlab BROWN_CORUNDUM_SLAB = new CorundumCrystalSlab();

    public static final CorundumCrystalStairs BLACK_CORUNDUM_STAIRS = new CorundumCrystalStairs();
    public static final CorundumCrystalStairs BLUE_CORUNDUM_STAIRS = new CorundumCrystalStairs();
    public static final CorundumCrystalStairs CYAN_CORUNDUM_STAIRS = new CorundumCrystalStairs();
    public static final CorundumCrystalStairs GREEN_CORUNDUM_STAIRS = new CorundumCrystalStairs();
    public static final CorundumCrystalStairs INDIGO_CORUNDUM_STAIRS = new CorundumCrystalStairs();
    public static final CorundumCrystalStairs ORANGE_CORUNDUM_STAIRS = new CorundumCrystalStairs();
    public static final CorundumCrystalStairs RED_CORUNDUM_STAIRS = new CorundumCrystalStairs();
    public static final CorundumCrystalStairs PINK_CORUNDUM_STAIRS = new CorundumCrystalStairs();
    public static final CorundumCrystalStairs WHITE_CORUNDUM_STAIRS = new CorundumCrystalStairs();
    public static final CorundumCrystalStairs YELLOW_CORUNDUM_STAIRS = new CorundumCrystalStairs();
    public static final CorundumCrystalStairs PURPLE_CORUNDUM_STAIRS = new CorundumCrystalStairs();
    public static final CorundumCrystalStairs BROWN_CORUNDUM_STAIRS = new CorundumCrystalStairs();

    public static final CorundumCrystalSlab BLACK_CRYSTAL_SLAB = new CorundumCrystalSlab();
    public static final CorundumCrystalSlab BLUE_CRYSTAL_SLAB = new CorundumCrystalSlab();
    public static final CorundumCrystalSlab CYAN_CRYSTAL_SLAB = new CorundumCrystalSlab();
    public static final CorundumCrystalSlab GREEN_CRYSTAL_SLAB = new CorundumCrystalSlab();
    public static final CorundumCrystalSlab INDIGO_CRYSTAL_SLAB = new CorundumCrystalSlab();
    public static final CorundumCrystalSlab ORANGE_CRYSTAL_SLAB = new CorundumCrystalSlab();
    public static final CorundumCrystalSlab RED_CRYSTAL_SLAB = new CorundumCrystalSlab();
    public static final CorundumCrystalSlab PINK_CRYSTAL_SLAB = new CorundumCrystalSlab();
    public static final CorundumCrystalSlab WHITE_CRYSTAL_SLAB = new CorundumCrystalSlab();
    public static final CorundumCrystalSlab YELLOW_CRYSTAL_SLAB = new CorundumCrystalSlab();
    public static final CorundumCrystalSlab PURPLE_CRYSTAL_SLAB = new CorundumCrystalSlab();
    public static final CorundumCrystalSlab BROWN_CRYSTAL_SLAB = new CorundumCrystalSlab();

    public static final CorundumCrystalStairs BLACK_CRYSTAL_STAIRS = new CorundumCrystalStairs();
    public static final CorundumCrystalStairs BLUE_CRYSTAL_STAIRS = new CorundumCrystalStairs();
    public static final CorundumCrystalStairs CYAN_CRYSTAL_STAIRS = new CorundumCrystalStairs();
    public static final CorundumCrystalStairs GREEN_CRYSTAL_STAIRS = new CorundumCrystalStairs();
    public static final CorundumCrystalStairs INDIGO_CRYSTAL_STAIRS = new CorundumCrystalStairs();
    public static final CorundumCrystalStairs ORANGE_CRYSTAL_STAIRS = new CorundumCrystalStairs();
    public static final CorundumCrystalStairs RED_CRYSTAL_STAIRS = new CorundumCrystalStairs();
    public static final CorundumCrystalStairs PINK_CRYSTAL_STAIRS = new CorundumCrystalStairs();
    public static final CorundumCrystalStairs WHITE_CRYSTAL_STAIRS = new CorundumCrystalStairs();
    public static final CorundumCrystalStairs YELLOW_CRYSTAL_STAIRS = new CorundumCrystalStairs();
    public static final CorundumCrystalStairs PURPLE_CRYSTAL_STAIRS = new CorundumCrystalStairs();
    public static final CorundumCrystalStairs BROWN_CRYSTAL_STAIRS = new CorundumCrystalStairs();

    public static final CrystalBlock RAINBOW_CRYSTAL = new CrystalBlock();
    public static final CorundumBlock RAINBOW_CORUNDUM = new CorundumBlock(false, 13);
    public static final CorundumBlock WAXED_RAINBOW_CORUNDUM = new CorundumBlock(true, 13);
    public static final CorundumCluster RAINBOW_CORUNDUM_CLUSTER = new CorundumCluster();
    public static final CorundumCrystalPane RAINBOW_CRYSTAL_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane RAINBOW_CORUNDUM_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalSlab RAINBOW_CORUNDUM_SLAB = new CorundumCrystalSlab();
    public static final CorundumCrystalStairs RAINBOW_CORUNDUM_STAIRS = new CorundumCrystalStairs();
    public static final CorundumCrystalSlab RAINBOW_CRYSTAL_SLAB = new CorundumCrystalSlab();
    public static final CorundumCrystalStairs RAINBOW_CRYSTAL_STAIRS = new CorundumCrystalStairs();

    public static final CrystalBlock DARK_CRYSTAL = new CrystalBlock();
    public static final CorundumBlock DARK_CORUNDUM = new CorundumBlock(false, 14);
    public static final CorundumBlock WAXED_DARK_CORUNDUM = new CorundumBlock(true, 14);
    public static final CorundumCluster DARK_CORUNDUM_CLUSTER = new CorundumCluster();
    public static final CorundumCrystalPane DARK_CRYSTAL_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalPane DARK_CORUNDUM_PANE = new CorundumCrystalPane();
    public static final CorundumCrystalSlab DARK_CORUNDUM_SLAB = new CorundumCrystalSlab();
    public static final CorundumCrystalStairs DARK_CORUNDUM_STAIRS = new CorundumCrystalStairs();
    public static final CorundumCrystalSlab DARK_CRYSTAL_SLAB = new CorundumCrystalSlab();
    public static final CorundumCrystalStairs DARK_CRYSTAL_STAIRS = new CorundumCrystalStairs();

    public static void registerBlocks() {
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(1)), ArrayDiscriminatorUtil.getCorundum[1]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(1)), new BlockItem(ArrayDiscriminatorUtil.getCorundum[1], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(2)), ArrayDiscriminatorUtil.getCorundum[2]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(2)), new BlockItem(ArrayDiscriminatorUtil.getCorundum[2], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(3)), ArrayDiscriminatorUtil.getCorundum[3]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(3)), new BlockItem(ArrayDiscriminatorUtil.getCorundum[3], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(4)), ArrayDiscriminatorUtil.getCorundum[4]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(4)), new BlockItem(ArrayDiscriminatorUtil.getCorundum[4], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(5)), ArrayDiscriminatorUtil.getCorundum[5]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(5)), new BlockItem(ArrayDiscriminatorUtil.getCorundum[5], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(6)), ArrayDiscriminatorUtil.getCorundum[6]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(6)), new BlockItem(ArrayDiscriminatorUtil.getCorundum[6], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(7)), ArrayDiscriminatorUtil.getCorundum[7]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(7)), new BlockItem(ArrayDiscriminatorUtil.getCorundum[7], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(8)), ArrayDiscriminatorUtil.getCorundum[8]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(8)), new BlockItem(ArrayDiscriminatorUtil.getCorundum[8], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(9)), ArrayDiscriminatorUtil.getCorundum[9]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(9)), new BlockItem(ArrayDiscriminatorUtil.getCorundum[9], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(10)), ArrayDiscriminatorUtil.getCorundum[10]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(10)), new BlockItem(ArrayDiscriminatorUtil.getCorundum[10], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(11)), ArrayDiscriminatorUtil.getCorundum[11]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(11)), new BlockItem(ArrayDiscriminatorUtil.getCorundum[11], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(12)), ArrayDiscriminatorUtil.getCorundum[12]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(12)), new BlockItem(ArrayDiscriminatorUtil.getCorundum[12], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        //Pane
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(1)),ArrayDiscriminatorUtil.getCorundumPane[1]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(1)), new BlockItem(ArrayDiscriminatorUtil.getCorundumPane[1], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(2)), ArrayDiscriminatorUtil.getCorundumPane[2]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(2)), new BlockItem(ArrayDiscriminatorUtil.getCorundumPane[2], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(3)), ArrayDiscriminatorUtil.getCorundumPane[3]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(3)), new BlockItem(ArrayDiscriminatorUtil.getCorundumPane[3], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(4)), ArrayDiscriminatorUtil.getCorundumPane[4]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(4)), new BlockItem(ArrayDiscriminatorUtil.getCorundumPane[4], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(5)), ArrayDiscriminatorUtil.getCorundumPane[5]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(5)), new BlockItem(ArrayDiscriminatorUtil.getCorundumPane[5], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(6)), ArrayDiscriminatorUtil.getCorundumPane[6]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(6)), new BlockItem(ArrayDiscriminatorUtil.getCorundumPane[6], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(7)), ArrayDiscriminatorUtil.getCorundumPane[7]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(7)), new BlockItem(ArrayDiscriminatorUtil.getCorundumPane[7], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(8)), ArrayDiscriminatorUtil.getCorundumPane[8]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(8)), new BlockItem(ArrayDiscriminatorUtil.getCorundumPane[8], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(9)), ArrayDiscriminatorUtil.getCorundumPane[9]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(9)), new BlockItem(ArrayDiscriminatorUtil.getCorundumPane[9], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(10)), ArrayDiscriminatorUtil.getCorundumPane[10]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(10)), new BlockItem(ArrayDiscriminatorUtil.getCorundumPane[10], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(11)),ArrayDiscriminatorUtil.getCorundumPane[11]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(11)), new BlockItem(ArrayDiscriminatorUtil.getCorundumPane[11], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(12)),ArrayDiscriminatorUtil.getCorundumPane[12]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(12)), new BlockItem(ArrayDiscriminatorUtil.getCorundumPane[12], new FabricItemSettings().group(ItemGroup.DECORATIONS)));

        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(1)), ArrayDiscriminatorUtil.getCrystal[1]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(1)), new BlockItem(ArrayDiscriminatorUtil.getCrystal[1], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(2)), ArrayDiscriminatorUtil.getCrystal[2]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(2)), new BlockItem(ArrayDiscriminatorUtil.getCrystal[2], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(3)), ArrayDiscriminatorUtil.getCrystal[3]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(3)), new BlockItem(ArrayDiscriminatorUtil.getCrystal[3], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(4)), ArrayDiscriminatorUtil.getCrystal[4]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(4)), new BlockItem(ArrayDiscriminatorUtil.getCrystal[4], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(5)), ArrayDiscriminatorUtil.getCrystal[5]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(5)), new BlockItem(ArrayDiscriminatorUtil.getCrystal[5], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(6)), ArrayDiscriminatorUtil.getCrystal[6]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(6)), new BlockItem(ArrayDiscriminatorUtil.getCrystal[6], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(7)), ArrayDiscriminatorUtil.getCrystal[7]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(7)), new BlockItem(ArrayDiscriminatorUtil.getCrystal[7], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(8)), ArrayDiscriminatorUtil.getCrystal[8]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(8)), new BlockItem(ArrayDiscriminatorUtil.getCrystal[8], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(9)), ArrayDiscriminatorUtil.getCrystal[9]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(9)), new BlockItem(ArrayDiscriminatorUtil.getCrystal[9], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(10)), ArrayDiscriminatorUtil.getCrystal[10]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(10)), new BlockItem(ArrayDiscriminatorUtil.getCrystal[10], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(11)), ArrayDiscriminatorUtil.getCrystal[11]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(11)), new BlockItem(ArrayDiscriminatorUtil.getCrystal[11], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(12)), ArrayDiscriminatorUtil.getCrystal[12]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(12)), new BlockItem(ArrayDiscriminatorUtil.getCrystal[12], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
           //Pane
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(1)),ArrayDiscriminatorUtil.getCrystalPane[1]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(1)), new BlockItem(ArrayDiscriminatorUtil.getCrystalPane[1], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(2)), ArrayDiscriminatorUtil.getCrystalPane[2]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(2)), new BlockItem(ArrayDiscriminatorUtil.getCrystalPane[2], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(3)), ArrayDiscriminatorUtil.getCrystalPane[3]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(3)), new BlockItem(ArrayDiscriminatorUtil.getCrystalPane[3], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(4)), ArrayDiscriminatorUtil.getCrystalPane[4]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(4)), new BlockItem(ArrayDiscriminatorUtil.getCrystalPane[4], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(5)), ArrayDiscriminatorUtil.getCrystalPane[5]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(5)), new BlockItem(ArrayDiscriminatorUtil.getCrystalPane[5], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(6)), ArrayDiscriminatorUtil.getCrystalPane[6]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(6)), new BlockItem(ArrayDiscriminatorUtil.getCrystalPane[6], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(7)), ArrayDiscriminatorUtil.getCrystalPane[7]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(7)), new BlockItem(ArrayDiscriminatorUtil.getCrystalPane[7], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(8)), ArrayDiscriminatorUtil.getCrystalPane[8]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(8)), new BlockItem(ArrayDiscriminatorUtil.getCrystalPane[8], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(9)), ArrayDiscriminatorUtil.getCrystalPane[9]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(9)), new BlockItem(ArrayDiscriminatorUtil.getCrystalPane[9], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(10)), ArrayDiscriminatorUtil.getCrystalPane[10]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(10)), new BlockItem(ArrayDiscriminatorUtil.getCrystalPane[10], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(11)),ArrayDiscriminatorUtil.getCrystalPane[11]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(11)), new BlockItem(ArrayDiscriminatorUtil.getCrystalPane[11], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(12)),ArrayDiscriminatorUtil.getCrystalPane[12]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(12)), new BlockItem(ArrayDiscriminatorUtil.getCrystalPane[12], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        //Clusters
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(1)),ArrayDiscriminatorUtil.getCorundumCluster[1]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(1)), new BlockItem(ArrayDiscriminatorUtil.getCorundumCluster[1], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(2)), ArrayDiscriminatorUtil.getCorundumCluster[2]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(2)), new BlockItem(ArrayDiscriminatorUtil.getCorundumCluster[2], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(3)), ArrayDiscriminatorUtil.getCorundumCluster[3]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(3)), new BlockItem(ArrayDiscriminatorUtil.getCorundumCluster[3], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(4)), ArrayDiscriminatorUtil.getCorundumCluster[4]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(4)), new BlockItem(ArrayDiscriminatorUtil.getCorundumCluster[4], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(5)), ArrayDiscriminatorUtil.getCorundumCluster[5]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(5)), new BlockItem(ArrayDiscriminatorUtil.getCorundumCluster[5], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(6)), ArrayDiscriminatorUtil.getCorundumCluster[6]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(6)), new BlockItem(ArrayDiscriminatorUtil.getCorundumCluster[6], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(7)), ArrayDiscriminatorUtil.getCorundumCluster[7]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(7)), new BlockItem(ArrayDiscriminatorUtil.getCorundumCluster[7], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(8)), ArrayDiscriminatorUtil.getCorundumCluster[8]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(8)), new BlockItem(ArrayDiscriminatorUtil.getCorundumCluster[8], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(9)), ArrayDiscriminatorUtil.getCorundumCluster[9]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(9)), new BlockItem(ArrayDiscriminatorUtil.getCorundumCluster[9], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(10)), ArrayDiscriminatorUtil.getCorundumCluster[10]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(10)), new BlockItem(ArrayDiscriminatorUtil.getCorundumCluster[10], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(11)),ArrayDiscriminatorUtil.getCorundumCluster[11]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(11)), new BlockItem(ArrayDiscriminatorUtil.getCorundumCluster[11], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(12)),ArrayDiscriminatorUtil.getCorundumCluster[12]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(12)), new BlockItem(ArrayDiscriminatorUtil.getCorundumCluster[12], new FabricItemSettings().group(ItemGroup.DECORATIONS)));


        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(1)), ArrayDiscriminatorUtil.getWaxedCorundum[1]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(1)), new BlockItem(ArrayDiscriminatorUtil.getWaxedCorundum[1], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        OxidizableBlocksRegistry.registerWaxableBlockPair(ArrayDiscriminatorUtil.getCorundum[1], ArrayDiscriminatorUtil.getWaxedCorundum[1]);
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(2)), ArrayDiscriminatorUtil.getWaxedCorundum[2]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(2)), new BlockItem(ArrayDiscriminatorUtil.getWaxedCorundum[2], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        OxidizableBlocksRegistry.registerWaxableBlockPair(ArrayDiscriminatorUtil.getCorundum[2], ArrayDiscriminatorUtil.getWaxedCorundum[2]);
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(3)), ArrayDiscriminatorUtil.getWaxedCorundum[3]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(3)), new BlockItem(ArrayDiscriminatorUtil.getWaxedCorundum[3], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        OxidizableBlocksRegistry.registerWaxableBlockPair(ArrayDiscriminatorUtil.getCorundum[3], ArrayDiscriminatorUtil.getWaxedCorundum[3]);
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(4)), ArrayDiscriminatorUtil.getWaxedCorundum[4]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(4)), new BlockItem(ArrayDiscriminatorUtil.getWaxedCorundum[4], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        OxidizableBlocksRegistry.registerWaxableBlockPair(ArrayDiscriminatorUtil.getCorundum[4], ArrayDiscriminatorUtil.getWaxedCorundum[4]);
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(5)), ArrayDiscriminatorUtil.getWaxedCorundum[5]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(5)), new BlockItem(ArrayDiscriminatorUtil.getWaxedCorundum[5], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        OxidizableBlocksRegistry.registerWaxableBlockPair(ArrayDiscriminatorUtil.getCorundum[5], ArrayDiscriminatorUtil.getWaxedCorundum[5]);
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(6)), ArrayDiscriminatorUtil.getWaxedCorundum[6]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(6)), new BlockItem(ArrayDiscriminatorUtil.getWaxedCorundum[6], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        OxidizableBlocksRegistry.registerWaxableBlockPair(ArrayDiscriminatorUtil.getCorundum[6], ArrayDiscriminatorUtil.getWaxedCorundum[6]);
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(7)), ArrayDiscriminatorUtil.getWaxedCorundum[7]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(7)), new BlockItem(ArrayDiscriminatorUtil.getWaxedCorundum[7], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        OxidizableBlocksRegistry.registerWaxableBlockPair(ArrayDiscriminatorUtil.getCorundum[7], ArrayDiscriminatorUtil.getWaxedCorundum[7]);
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(8)), ArrayDiscriminatorUtil.getWaxedCorundum[8]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(8)), new BlockItem(ArrayDiscriminatorUtil.getWaxedCorundum[8], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        OxidizableBlocksRegistry.registerWaxableBlockPair(ArrayDiscriminatorUtil.getCorundum[8], ArrayDiscriminatorUtil.getWaxedCorundum[8]);
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(9)), ArrayDiscriminatorUtil.getWaxedCorundum[9]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(9)), new BlockItem(ArrayDiscriminatorUtil.getWaxedCorundum[9], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        OxidizableBlocksRegistry.registerWaxableBlockPair(ArrayDiscriminatorUtil.getCorundum[9], ArrayDiscriminatorUtil.getWaxedCorundum[9]);
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(10)), ArrayDiscriminatorUtil.getWaxedCorundum[10]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(10)), new BlockItem(ArrayDiscriminatorUtil.getWaxedCorundum[10], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        OxidizableBlocksRegistry.registerWaxableBlockPair(ArrayDiscriminatorUtil.getCorundum[10], ArrayDiscriminatorUtil.getWaxedCorundum[10]);
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(11)), ArrayDiscriminatorUtil.getWaxedCorundum[11]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(11)), new BlockItem(ArrayDiscriminatorUtil.getWaxedCorundum[11], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        OxidizableBlocksRegistry.registerWaxableBlockPair(ArrayDiscriminatorUtil.getCorundum[11], ArrayDiscriminatorUtil.getWaxedCorundum[11]);
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(12)), ArrayDiscriminatorUtil.getWaxedCorundum[12]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(12)), new BlockItem(ArrayDiscriminatorUtil.getWaxedCorundum[12], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        OxidizableBlocksRegistry.registerWaxableBlockPair(ArrayDiscriminatorUtil.getCorundum[12], ArrayDiscriminatorUtil.getWaxedCorundum[12]);

        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumStairs(1)),ArrayDiscriminatorUtil.getCorundumStairs[1]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumStairs(1)), new BlockItem(ArrayDiscriminatorUtil.getCorundumStairs[1], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumStairs(2)), ArrayDiscriminatorUtil.getCorundumStairs[2]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumStairs(2)), new BlockItem(ArrayDiscriminatorUtil.getCorundumStairs[2], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumStairs(3)), ArrayDiscriminatorUtil.getCorundumStairs[3]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumStairs(3)), new BlockItem(ArrayDiscriminatorUtil.getCorundumStairs[3], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumStairs(4)), ArrayDiscriminatorUtil.getCorundumStairs[4]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumStairs(4)), new BlockItem(ArrayDiscriminatorUtil.getCorundumStairs[4], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumStairs(5)), ArrayDiscriminatorUtil.getCorundumStairs[5]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumStairs(5)), new BlockItem(ArrayDiscriminatorUtil.getCorundumStairs[5], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumStairs(6)), ArrayDiscriminatorUtil.getCorundumStairs[6]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumStairs(6)), new BlockItem(ArrayDiscriminatorUtil.getCorundumStairs[6], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumStairs(7)), ArrayDiscriminatorUtil.getCorundumStairs[7]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumStairs(7)), new BlockItem(ArrayDiscriminatorUtil.getCorundumStairs[7], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumStairs(8)), ArrayDiscriminatorUtil.getCorundumStairs[8]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumStairs(8)), new BlockItem(ArrayDiscriminatorUtil.getCorundumStairs[8], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumStairs(9)), ArrayDiscriminatorUtil.getCorundumStairs[9]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumStairs(9)), new BlockItem(ArrayDiscriminatorUtil.getCorundumStairs[9], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumStairs(10)), ArrayDiscriminatorUtil.getCorundumStairs[10]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumStairs(10)), new BlockItem(ArrayDiscriminatorUtil.getCorundumStairs[10], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumStairs(11)),ArrayDiscriminatorUtil.getCorundumStairs[11]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumStairs(11)), new BlockItem(ArrayDiscriminatorUtil.getCorundumStairs[11], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumStairs(12)),ArrayDiscriminatorUtil.getCorundumStairs[12]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumStairs(12)), new BlockItem(ArrayDiscriminatorUtil.getCorundumStairs[12], new FabricItemSettings().group(ItemGroup.DECORATIONS)));

        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumSlab(1)),ArrayDiscriminatorUtil.getCorundumSlab[1]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumSlab(1)), new BlockItem(ArrayDiscriminatorUtil.getCorundumSlab[1], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumSlab(2)), ArrayDiscriminatorUtil.getCorundumSlab[2]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumSlab(2)), new BlockItem(ArrayDiscriminatorUtil.getCorundumSlab[2], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumSlab(3)), ArrayDiscriminatorUtil.getCorundumSlab[3]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumSlab(3)), new BlockItem(ArrayDiscriminatorUtil.getCorundumSlab[3], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumSlab(4)), ArrayDiscriminatorUtil.getCorundumSlab[4]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumSlab(4)), new BlockItem(ArrayDiscriminatorUtil.getCorundumSlab[4], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumSlab(5)), ArrayDiscriminatorUtil.getCorundumSlab[5]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumSlab(5)), new BlockItem(ArrayDiscriminatorUtil.getCorundumSlab[5], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumSlab(6)), ArrayDiscriminatorUtil.getCorundumSlab[6]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumSlab(6)), new BlockItem(ArrayDiscriminatorUtil.getCorundumSlab[6], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumSlab(7)), ArrayDiscriminatorUtil.getCorundumSlab[7]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumSlab(7)), new BlockItem(ArrayDiscriminatorUtil.getCorundumSlab[7], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumSlab(8)), ArrayDiscriminatorUtil.getCorundumSlab[8]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumSlab(8)), new BlockItem(ArrayDiscriminatorUtil.getCorundumSlab[8], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumSlab(9)), ArrayDiscriminatorUtil.getCorundumSlab[9]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumSlab(9)), new BlockItem(ArrayDiscriminatorUtil.getCorundumSlab[9], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumSlab(10)), ArrayDiscriminatorUtil.getCorundumSlab[10]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumSlab(10)), new BlockItem(ArrayDiscriminatorUtil.getCorundumSlab[10], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumSlab(11)),ArrayDiscriminatorUtil.getCorundumSlab[11]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumSlab(11)), new BlockItem(ArrayDiscriminatorUtil.getCorundumSlab[11], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumSlab(12)),ArrayDiscriminatorUtil.getCorundumSlab[12]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumSlab(12)), new BlockItem(ArrayDiscriminatorUtil.getCorundumSlab[12], new FabricItemSettings().group(ItemGroup.DECORATIONS)));

        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalStairs(1)),ArrayDiscriminatorUtil.getCrystalStairs[1]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalStairs(1)), new BlockItem(ArrayDiscriminatorUtil.getCrystalStairs[1], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalStairs(2)), ArrayDiscriminatorUtil.getCrystalStairs[2]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalStairs(2)), new BlockItem(ArrayDiscriminatorUtil.getCrystalStairs[2], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalStairs(3)), ArrayDiscriminatorUtil.getCrystalStairs[3]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalStairs(3)), new BlockItem(ArrayDiscriminatorUtil.getCrystalStairs[3], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalStairs(4)), ArrayDiscriminatorUtil.getCrystalStairs[4]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalStairs(4)), new BlockItem(ArrayDiscriminatorUtil.getCrystalStairs[4], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalStairs(5)), ArrayDiscriminatorUtil.getCrystalStairs[5]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalStairs(5)), new BlockItem(ArrayDiscriminatorUtil.getCrystalStairs[5], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalStairs(6)), ArrayDiscriminatorUtil.getCrystalStairs[6]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalStairs(6)), new BlockItem(ArrayDiscriminatorUtil.getCrystalStairs[6], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalStairs(7)), ArrayDiscriminatorUtil.getCrystalStairs[7]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalStairs(7)), new BlockItem(ArrayDiscriminatorUtil.getCrystalStairs[7], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalStairs(8)), ArrayDiscriminatorUtil.getCrystalStairs[8]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalStairs(8)), new BlockItem(ArrayDiscriminatorUtil.getCrystalStairs[8], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalStairs(9)), ArrayDiscriminatorUtil.getCrystalStairs[9]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalStairs(9)), new BlockItem(ArrayDiscriminatorUtil.getCrystalStairs[9], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalStairs(10)), ArrayDiscriminatorUtil.getCrystalStairs[10]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalStairs(10)), new BlockItem(ArrayDiscriminatorUtil.getCrystalStairs[10], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalStairs(11)),ArrayDiscriminatorUtil.getCrystalStairs[11]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalStairs(11)), new BlockItem(ArrayDiscriminatorUtil.getCrystalStairs[11], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalStairs(12)),ArrayDiscriminatorUtil.getCrystalStairs[12]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalStairs(12)), new BlockItem(ArrayDiscriminatorUtil.getCrystalStairs[12], new FabricItemSettings().group(ItemGroup.DECORATIONS)));

        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalSlab(1)),ArrayDiscriminatorUtil.getCrystalSlab[1]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalSlab(1)), new BlockItem(ArrayDiscriminatorUtil.getCrystalSlab[1], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalSlab(2)), ArrayDiscriminatorUtil.getCrystalSlab[2]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalSlab(2)), new BlockItem(ArrayDiscriminatorUtil.getCrystalSlab[2], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalSlab(3)), ArrayDiscriminatorUtil.getCrystalSlab[3]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalSlab(3)), new BlockItem(ArrayDiscriminatorUtil.getCrystalSlab[3], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalSlab(4)), ArrayDiscriminatorUtil.getCrystalSlab[4]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalSlab(4)), new BlockItem(ArrayDiscriminatorUtil.getCrystalSlab[4], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalSlab(5)), ArrayDiscriminatorUtil.getCrystalSlab[5]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalSlab(5)), new BlockItem(ArrayDiscriminatorUtil.getCrystalSlab[5], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalSlab(6)), ArrayDiscriminatorUtil.getCrystalSlab[6]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalSlab(6)), new BlockItem(ArrayDiscriminatorUtil.getCrystalSlab[6], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalSlab(7)), ArrayDiscriminatorUtil.getCrystalSlab[7]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalSlab(7)), new BlockItem(ArrayDiscriminatorUtil.getCrystalSlab[7], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalSlab(8)), ArrayDiscriminatorUtil.getCrystalSlab[8]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalSlab(8)), new BlockItem(ArrayDiscriminatorUtil.getCrystalSlab[8], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalSlab(9)), ArrayDiscriminatorUtil.getCrystalSlab[9]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalSlab(9)), new BlockItem(ArrayDiscriminatorUtil.getCrystalSlab[9], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalSlab(10)), ArrayDiscriminatorUtil.getCrystalSlab[10]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalSlab(10)), new BlockItem(ArrayDiscriminatorUtil.getCrystalSlab[10], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalSlab(11)),ArrayDiscriminatorUtil.getCrystalSlab[11]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalSlab(11)), new BlockItem(ArrayDiscriminatorUtil.getCrystalSlab[11], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalSlab(12)),ArrayDiscriminatorUtil.getCrystalSlab[12]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalSlab(12)), new BlockItem(ArrayDiscriminatorUtil.getCrystalSlab[12], new FabricItemSettings().group(ItemGroup.DECORATIONS)));

        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(13)), ArrayDiscriminatorUtil.getCrystal[13]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(13)), new BlockItem(ArrayDiscriminatorUtil.getCrystal[13], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(13)), ArrayDiscriminatorUtil.getWaxedCorundum[13]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(13)), new BlockItem(ArrayDiscriminatorUtil.getWaxedCorundum[13], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        OxidizableBlocksRegistry.registerWaxableBlockPair(ArrayDiscriminatorUtil.getCorundum[13], ArrayDiscriminatorUtil.getWaxedCorundum[13]);
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(13)), ArrayDiscriminatorUtil.getCorundum[13]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(13)), new BlockItem(ArrayDiscriminatorUtil.getCorundum[13], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(13)),ArrayDiscriminatorUtil.getCorundumCluster[13]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(13)), new BlockItem(ArrayDiscriminatorUtil.getCorundumCluster[13], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(13)),ArrayDiscriminatorUtil.getCorundumPane[13]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(13)), new BlockItem(ArrayDiscriminatorUtil.getCorundumPane[13], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(13)),ArrayDiscriminatorUtil.getCrystalPane[13]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(13)), new BlockItem(ArrayDiscriminatorUtil.getCrystalPane[13], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalSlab(13)),ArrayDiscriminatorUtil.getCrystalSlab[13]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalSlab(13)), new BlockItem(ArrayDiscriminatorUtil.getCrystalSlab[13], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalStairs(13)),ArrayDiscriminatorUtil.getCrystalStairs[13]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalStairs(13)), new BlockItem(ArrayDiscriminatorUtil.getCrystalStairs[13], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumSlab(13)),ArrayDiscriminatorUtil.getCorundumSlab[13]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumSlab(13)), new BlockItem(ArrayDiscriminatorUtil.getCorundumSlab[13], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumStairs(13)),ArrayDiscriminatorUtil.getCorundumStairs[13]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumStairs(13)), new BlockItem(ArrayDiscriminatorUtil.getCorundumStairs[13], new FabricItemSettings().group(ItemGroup.DECORATIONS)));

        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(14)), ArrayDiscriminatorUtil.getCrystal[14]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystal(14)), new BlockItem(ArrayDiscriminatorUtil.getCrystal[14], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(14)), ArrayDiscriminatorUtil.getWaxedCorundum[14]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getWaxedCorundum(14)), new BlockItem(ArrayDiscriminatorUtil.getWaxedCorundum[14], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        OxidizableBlocksRegistry.registerWaxableBlockPair(ArrayDiscriminatorUtil.getCorundum[14], ArrayDiscriminatorUtil.getWaxedCorundum[14]);
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(14)), ArrayDiscriminatorUtil.getCorundum[14]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundum(14)), new BlockItem(ArrayDiscriminatorUtil.getCorundum[14], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(14)),ArrayDiscriminatorUtil.getCorundumCluster[14]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumCluster(14)), new BlockItem(ArrayDiscriminatorUtil.getCorundumCluster[14], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(14)),ArrayDiscriminatorUtil.getCorundumPane[14]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumPane(14)), new BlockItem(ArrayDiscriminatorUtil.getCorundumPane[14], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(14)),ArrayDiscriminatorUtil.getCrystalPane[14]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalPane(14)), new BlockItem(ArrayDiscriminatorUtil.getCrystalPane[14], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalSlab(14)),ArrayDiscriminatorUtil.getCrystalSlab[14]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalSlab(14)), new BlockItem(ArrayDiscriminatorUtil.getCrystalSlab[14], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalStairs(14)),ArrayDiscriminatorUtil.getCrystalStairs[14]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCrystalStairs(14)), new BlockItem(ArrayDiscriminatorUtil.getCrystalStairs[14], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumSlab(14)),ArrayDiscriminatorUtil.getCorundumSlab[14]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumSlab(14)), new BlockItem(ArrayDiscriminatorUtil.getCorundumSlab[14], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
        Registry.register(Registry.BLOCK, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumStairs(14)),ArrayDiscriminatorUtil.getCorundumStairs[14]);
        Registry.register(Registry.ITEM, new Identifier(IdentifierUtil.ID, ArrayDiscriminatorUtil.getCorundumStairs(14)), new BlockItem(ArrayDiscriminatorUtil.getCorundumStairs[14], new FabricItemSettings().group(ItemGroup.DECORATIONS)));
    }
}
