package net.fluffybumblebee.quarkcrystals;

import net.fabricmc.api.ClientModInitializer;
import net.fabricmc.fabric.api.blockrenderlayer.v1.BlockRenderLayerMap;
import net.fluffybumblebee.quarkcrystals.util.ArrayDiscriminatorUtil;
import net.minecraft.client.render.RenderLayer;

public class QuarkCrystalsClient implements ClientModInitializer {

    @Override public void onInitializeClient() {
        BlockRenderLayerMap.INSTANCE.putBlocks(RenderLayer.getCutout(),
                ArrayDiscriminatorUtil.getCorundumCluster[1],
                ArrayDiscriminatorUtil.getCorundumCluster[2],
                ArrayDiscriminatorUtil.getCorundumCluster[3],
                ArrayDiscriminatorUtil.getCorundumCluster[4],
                ArrayDiscriminatorUtil.getCorundumCluster[5],
                ArrayDiscriminatorUtil.getCorundumCluster[6],
                ArrayDiscriminatorUtil.getCorundumCluster[7],
                ArrayDiscriminatorUtil.getCorundumCluster[8],
                ArrayDiscriminatorUtil.getCorundumCluster[9],
                ArrayDiscriminatorUtil.getCorundumCluster[10],
                ArrayDiscriminatorUtil.getCorundumCluster[11],
                ArrayDiscriminatorUtil.getCorundumCluster[12],
                ArrayDiscriminatorUtil.getCorundumCluster[13],
                ArrayDiscriminatorUtil.getCorundumCluster[14]
        );
        BlockRenderLayerMap.INSTANCE.putBlocks(RenderLayer.getTranslucent(),

                ArrayDiscriminatorUtil.getCorundum[1],
                ArrayDiscriminatorUtil.getCorundum[2],
                ArrayDiscriminatorUtil.getCorundum[3],
                ArrayDiscriminatorUtil.getCorundum[4],
                ArrayDiscriminatorUtil.getCorundum[5],
                ArrayDiscriminatorUtil.getCorundum[6],
                ArrayDiscriminatorUtil.getCorundum[7],
                ArrayDiscriminatorUtil.getCorundum[8],
                ArrayDiscriminatorUtil.getCorundum[9],
                ArrayDiscriminatorUtil.getCorundum[10],
                ArrayDiscriminatorUtil.getCorundum[11],
                ArrayDiscriminatorUtil.getCorundum[12],

                ArrayDiscriminatorUtil.getCorundumPane[1],
                ArrayDiscriminatorUtil.getCorundumPane[2],
                ArrayDiscriminatorUtil.getCorundumPane[3],
                ArrayDiscriminatorUtil.getCorundumPane[4],
                ArrayDiscriminatorUtil.getCorundumPane[5],
                ArrayDiscriminatorUtil.getCorundumPane[6],
                ArrayDiscriminatorUtil.getCorundumPane[7],
                ArrayDiscriminatorUtil.getCorundumPane[8],
                ArrayDiscriminatorUtil.getCorundumPane[9],
                ArrayDiscriminatorUtil.getCorundumPane[10],
                ArrayDiscriminatorUtil.getCorundumPane[11],
                ArrayDiscriminatorUtil.getCorundumPane[12],

                ArrayDiscriminatorUtil.getCrystal[1],
                ArrayDiscriminatorUtil.getCrystal[2],
                ArrayDiscriminatorUtil.getCrystal[3],
                ArrayDiscriminatorUtil.getCrystal[4],
                ArrayDiscriminatorUtil.getCrystal[5],
                ArrayDiscriminatorUtil.getCrystal[6],
                ArrayDiscriminatorUtil.getCrystal[7],
                ArrayDiscriminatorUtil.getCrystal[8],
                ArrayDiscriminatorUtil.getCrystal[9],
                ArrayDiscriminatorUtil.getCrystal[10],
                ArrayDiscriminatorUtil.getCrystal[11],
                ArrayDiscriminatorUtil.getCrystal[12],

                ArrayDiscriminatorUtil.getCrystalPane[1],
                ArrayDiscriminatorUtil.getCrystalPane[2],
                ArrayDiscriminatorUtil.getCrystalPane[3],
                ArrayDiscriminatorUtil.getCrystalPane[4],
                ArrayDiscriminatorUtil.getCrystalPane[5],
                ArrayDiscriminatorUtil.getCrystalPane[6],
                ArrayDiscriminatorUtil.getCrystalPane[7],
                ArrayDiscriminatorUtil.getCrystalPane[8],
                ArrayDiscriminatorUtil.getCrystalPane[9],
                ArrayDiscriminatorUtil.getCrystalPane[10],
                ArrayDiscriminatorUtil.getCrystalPane[11],
                ArrayDiscriminatorUtil.getCrystalPane[12],

                ArrayDiscriminatorUtil.getWaxedCorundum[1],
                ArrayDiscriminatorUtil.getWaxedCorundum[2],
                ArrayDiscriminatorUtil.getWaxedCorundum[3],
                ArrayDiscriminatorUtil.getWaxedCorundum[4],
                ArrayDiscriminatorUtil.getWaxedCorundum[5],
                ArrayDiscriminatorUtil.getWaxedCorundum[6],
                ArrayDiscriminatorUtil.getWaxedCorundum[7],
                ArrayDiscriminatorUtil.getWaxedCorundum[8],
                ArrayDiscriminatorUtil.getWaxedCorundum[9],
                ArrayDiscriminatorUtil.getWaxedCorundum[10],
                ArrayDiscriminatorUtil.getWaxedCorundum[11],
                ArrayDiscriminatorUtil.getWaxedCorundum[12],

                ArrayDiscriminatorUtil.getCorundumStairs[1],
                ArrayDiscriminatorUtil.getCorundumStairs[2],
                ArrayDiscriminatorUtil.getCorundumStairs[3],
                ArrayDiscriminatorUtil.getCorundumStairs[4],
                ArrayDiscriminatorUtil.getCorundumStairs[5],
                ArrayDiscriminatorUtil.getCorundumStairs[6],
                ArrayDiscriminatorUtil.getCorundumStairs[7],
                ArrayDiscriminatorUtil.getCorundumStairs[8],
                ArrayDiscriminatorUtil.getCorundumStairs[9],
                ArrayDiscriminatorUtil.getCorundumStairs[10],
                ArrayDiscriminatorUtil.getCorundumStairs[11],
                ArrayDiscriminatorUtil.getCorundumStairs[12],

                ArrayDiscriminatorUtil.getCorundumSlab[1],
                ArrayDiscriminatorUtil.getCorundumSlab[2],
                ArrayDiscriminatorUtil.getCorundumSlab[3],
                ArrayDiscriminatorUtil.getCorundumSlab[4],
                ArrayDiscriminatorUtil.getCorundumSlab[5],
                ArrayDiscriminatorUtil.getCorundumSlab[6],
                ArrayDiscriminatorUtil.getCorundumSlab[7],
                ArrayDiscriminatorUtil.getCorundumSlab[8],
                ArrayDiscriminatorUtil.getCorundumSlab[9],
                ArrayDiscriminatorUtil.getCorundumSlab[10],
                ArrayDiscriminatorUtil.getCorundumSlab[11],
                ArrayDiscriminatorUtil.getCorundumSlab[12],

                ArrayDiscriminatorUtil.getCrystalStairs[1],
                ArrayDiscriminatorUtil.getCrystalStairs[2],
                ArrayDiscriminatorUtil.getCrystalStairs[3],
                ArrayDiscriminatorUtil.getCrystalStairs[4],
                ArrayDiscriminatorUtil.getCrystalStairs[5],
                ArrayDiscriminatorUtil.getCrystalStairs[6],
                ArrayDiscriminatorUtil.getCrystalStairs[7],
                ArrayDiscriminatorUtil.getCrystalStairs[8],
                ArrayDiscriminatorUtil.getCrystalStairs[9],
                ArrayDiscriminatorUtil.getCrystalStairs[10],
                ArrayDiscriminatorUtil.getCrystalStairs[11],
                ArrayDiscriminatorUtil.getCrystalStairs[12],

                ArrayDiscriminatorUtil.getCrystalSlab[1],
                ArrayDiscriminatorUtil.getCrystalSlab[2],
                ArrayDiscriminatorUtil.getCrystalSlab[3],
                ArrayDiscriminatorUtil.getCrystalSlab[4],
                ArrayDiscriminatorUtil.getCrystalSlab[5],
                ArrayDiscriminatorUtil.getCrystalSlab[6],
                ArrayDiscriminatorUtil.getCrystalSlab[7],
                ArrayDiscriminatorUtil.getCrystalSlab[8],
                ArrayDiscriminatorUtil.getCrystalSlab[9],
                ArrayDiscriminatorUtil.getCrystalSlab[10],
                ArrayDiscriminatorUtil.getCrystalSlab[11],
                ArrayDiscriminatorUtil.getCrystalSlab[12],

                ArrayDiscriminatorUtil.getCrystal[13],
                ArrayDiscriminatorUtil.getCorundum[13],
                ArrayDiscriminatorUtil.getCorundumPane[13],
                ArrayDiscriminatorUtil.getCrystalPane[13],
                ArrayDiscriminatorUtil.getWaxedCorundum[13],
                ArrayDiscriminatorUtil.getCorundumStairs[13],
                ArrayDiscriminatorUtil.getCorundumSlab[13],
                ArrayDiscriminatorUtil.getCrystalStairs[13],
                ArrayDiscriminatorUtil.getCrystalSlab[13],

                ArrayDiscriminatorUtil.getCrystal[14],
                ArrayDiscriminatorUtil.getCorundum[14],
                ArrayDiscriminatorUtil.getCorundumPane[14],
                ArrayDiscriminatorUtil.getCrystalPane[14],
                ArrayDiscriminatorUtil.getWaxedCorundum[14],
                ArrayDiscriminatorUtil.getCorundumStairs[14],
                ArrayDiscriminatorUtil.getCorundumSlab[14],
                ArrayDiscriminatorUtil.getCrystalStairs[14],
                ArrayDiscriminatorUtil.getCrystalSlab[14]
                );
    }
}
